### PR TITLE
Citation graphs

### PR DESCRIPTION
**Pull request by JakeStevens**
I have added support for the citation graph networks in DGL for node classification in single large graphs, as referred to in issue #3 , for the GAT, GCN, and GraphSage architectures. I have also added a switch to these architectures to use a more optimized version of the layers from within DGL. These switches are unused in the already existing code so there should be no changes there. When using the DGL switch, all results on the CORA, CITESEER, and PUBMED datasets are relatively close to those reported by DGL. When using the custom code from Benchmarking GNNs, they are also relatively close, but exhibit much slower performance.

Note that I have not tried any ablation studies on the citation workloads using the different graph vs batch norms or residual connections or anything like that, as I am not really investigating algorithmic performance but rather hardware performance. However, hopefully this could provide a good starting place for people interested in doing so, such as @saaay71.

### CODE REVIEW

**Comment by vijaydwivedi75** [comment]
Thanks for the contribution, @JakeStevens!

**One comment:**
In the `'layers/gcn_layer.py'`, you write "the graph norm is already done in builtin". See snippet below.
```
        if self.dgl_builtin == False:
            if self.graph_norm:
                feature = feature * snorm_n # normalize activation w.r.t. graph size
            g.ndata['h'] = feature
            g.update_all(msg, self.reduce)
            g.apply_nodes(func=self.apply_mod)
            h = g.ndata['h'] # result of graph convolution
            # Note that is already done in builtin
            if self.graph_norm:
                h = h * snorm_n # normalize activation w.r.t. graph size
        else:
            h = self.conv(g, feature)
```

Although the graph norm is irrelevant for single graph tasks, these are useful when batches of graphs are fed to a GNN. Please refer to the paper.

Therefore, I think the option for normalizing activations w.r.t. graph size should be in the code segment which uses the dgl builtin method, (in the `else` part).

**Comment by vijaydwivedi75** [comment]
Thanks for the contribution, @JakeStevens!

**One comment:**
In the `'layers/gcn_layer.py'`, you write "the graph norm is already done in builtin". See snippet below.
```
        if self.dgl_builtin == False:
            if self.graph_norm:
                feature = feature * snorm_n # normalize activation w.r.t. graph size
            g.ndata['h'] = feature
            g.update_all(msg, self.reduce)
            g.apply_nodes(func=self.apply_mod)
            h = g.ndata['h'] # result of graph convolution
            # Note that is already done in builtin
            if self.graph_norm:
                h = h * snorm_n # normalize activation w.r.t. graph size
        else:
            h = self.conv(g, feature)
```

Although the graph norm may be irrelevant for single graph tasks (because all node activations would be scaled with the same value), these are useful when batches of graphs are fed to a GNN. Please refer to the paper.

Therefore, I think the option for normalizing activations w.r.t. graph size should be in the code segment which uses the dgl builtin method, (in the `else` part).

**Comment by JakeStevens** [comment]
Ah thanks for pointing that out. I got confused by the DGL implementation's use of "norm" in their code, but I see now that theirs is normalized by the number of edges as opposed to the root of number of nodes. I have fixed that now.

**Comment by chaitjo** [comment]
Thanks for the contribution, @JakeStevens ! 

@vijaydwivedi75, Maybe it will be beneficial to include a `CONTRIBUTING.md` file to encourage further contributions and improve workflow. 

For e.g. do we want PRs which implement single feature to squash all commits for keeping commit history concise, or do we want all the details.

**Pull request merged**
