### PR TITLE
Use builtin reducers for 0.5.2

### PR DESCRIPTION
**Pull request by BarclayII**
This PR changes the reducers of GraphSage/GCN/GatedGCN from user-defined functions to builtin functions.  Such changes brought a significant speedup for both 0.5.2 and 0.4.2 on these models:

EDIT: The dataset is SBM_PATTERN-100k and I ran the benchmark on a g3.16x AWS instance.

| Model | 0.4.2 w/ UDF | 0.4.2 w/ builtin reducers | DGL-master w/ UDF | DGL-master w/ builtin reducers |
|:-:|:-:|:-:|:-:|:-:|
| GraphSage | 326.21 | 43.0335 | 316.99 | 17.8404 |
| GatedGCN | 573.42 | 207.3135 | 598.05 | 177.4308 |

DGL-master represents the current master branch of DGL that incorporated some performance optimization on graph batching and readouts (today).  The code should be available in the upcoming nightly build 201125.

This PR is for DGL 0.5.2.  I'll submit a separate PR for 0.4.2 once this PR has been reviewed since the code changes are exactly the same.

### CODE REVIEW

**Comment by chaitjo** [comment]
Thanks for the contribution, the speedup looks super good!!

1. Which dataset are you reporting the times on?
2. For most models/convolutions such as Sage and GAT, we are able to pass a flag `dgl_builtin=True` to use the optimized DGL layers within Benchmarking-GNNs. Would you be open to including GatedGCN as an official layer in DGL?

**Comment by BarclayII** [comment]
@chaitjo The dataset is SBM_PATTERN-100k.  I have updated the PR description.

DGL does come with a [Gated Graph Convolution Layer](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatedgraphconv.py) but it seems different from yours, so please feel free to open a PR whenever you feel like to.

Thanks.

**Comment by yzh119** [comment]
@chaitjo what this PR did is to change the message functions you defined in your codebase with dgl's (functionality equivalent) builtin functions (which is the recommended way to use dgl) rather than use DGL's optimized layers.
This being said, what DGL optimizes is not the layers but the builtin-functions, but unfortunately you did not fully utilize its efficiency before:)

This PR neither changes the semantics of your models nor introduces extra dependencies (such as dgl's nn modules) and I think you do not need to set the flag. If you can confirm that all models produces the same accuracy as before then I think you can safely merge this PR.

**Comment by vijaydwivedi75** [comment]
Thanks @yzh119 @BarclayII !

**Pull request merged**
